### PR TITLE
Add arch for arm, ppc64le

### PR DESCRIPTION
**Pull request by pavelzw**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by wolfv** [comment]
Thanks @pavelzw :)

**Comment by pavelzw** [comment]
Unfortunately, we depend on `ring` (among others in rattler -> apple-codesign) which currently does not yet have ppc64le support. 

https://github.com/briansmith/ring/pull/1057

**Comment by pavelzw** [comment]
@wolfv this is ready for review now 😅

**Review by ruben-arts — APPROVED** [review]
Awesome @pavelzw, Looks good to me! I've never added a aarch64 build so I'll wait for @wolfv 's review with the merge.

**Comment by wolfv** [comment]
AWESOME!

**Pull request merged**
